version: '3.8'

services:
  jira-backend:
    container_name: jira-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - jira-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  jira-db:
    container_name: jira-db
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
